image:
  tag: 0.1.0
ingress:
  hosts:
    - host: api.training.sneakertail.online
      paths:
        - path: /api/trainer
          pathType: Prefix
  tls:
    - secretName: sneakertail-cert
      hosts:
        - api.training.sneakertail.online
env:
  DB_USER: "ctmp3-workload-identity"
keyvaultName: "ctmp3-kv"
workloadIdentity:
  clientId: ""
