image:
  repository: ctmp3acrdev.azurecr.io/student-service
  tag: 0.0.15
ingress:
  hosts:
    - host: api.dev.training.sneakertail.online
      paths:
        - path: /api/student
          pathType: Prefix
  tls:
    - secretName: sneakertail-cert
      hosts:
        - api.dev.training.sneakertail.online
env:
  DB_USER: "ctmp3dev-workload-identity"
keyvaultName: "ctmp3dev-kv"
workloadIdentity:
  clientId: "e0533907-ad4c-480d-b281-ca733000f3a6"
