image:
  tag: 0.0.1
ingress:
  hosts:
    - host: dev.training.sneakertail.online
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: sneakertail-cert-dev
      hosts:
        - dev.training.sneakertail.online
