image:
  tag: 0.18.0
ingress:
  hosts:
    - host: training.sneakertail.online
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: sneakertail-cert
      hosts:
        - training.sneakertail.online
